Feature/html01
sassamori/takaharusasamori pull request #1
Opened 2020-07-23 10:40 UTC by sassamori

NRI課題のHTMLまでを作成しました。

2020-07-24 01:53 UTC, n06Ar requested changes
細かいところはコード上で、全体的な指摘を下記に記載しました
ご確認をお願いします

- Webページのメインコンテンツであることを示すmainタグを追加してください
- imgタグのalt属性が含まれていません、画像が見れなくても内容が伝わる必要がある情報の場合は入力してください
  - クローラーやスクリーンリーダーが読めるようにするために追記してください
- 全体的に`h`タグ系の順序が違和感があるため修正してください
  - `h1`タグより先に`h2`がある場合は、章、節、項の文書構成でいうところの節から始まっている状態になるためです

2020-07-24 01:53 UTC, n06Ar commented on html-nri/index.html
> +        <h2><a href="#"><img src="images/nri_logo.jpg" alt="NRI" width="60" height="30"></a></h2>
`h1`タグを使用してください
`h2`から始めると、章、節、項の文書構成でいうところの節から始まっている状態になるためです

2020-07-24 01:53 UTC, n06Ar commented on html-nri/index.html
> +    <nav class="breadcrumbs">
パンくずは、ナビゲーション系の物なため`header`タグの中に入れてください

2020-07-24 01:53 UTC, n06Ar commented on html-nri/index.html
> +    <title>NRIの強み：ビジネスモデルの特徴</title>
`meta`タグの`description`と`keywords`、OGP系のタグがないので追加をお願いします

2020-07-24 01:59 UTC, n06Ar commented on html-nri/index.html
> +        <nav class="share">
in my opinionです（つまり修正は必須ではないという意味です）
share系のボタンはナビゲーションではないので、`div`タグでも良いです

2020-07-24 04:23 UTC, sassamori commented on html-nri/index.html
> +        <h2><a href="#"><img src="images/nri_logo.jpg" alt="NRI" width="60" height="30"></a></h2>
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/1/commits/ff24402630471d60481fbf3a85e07e3544577524

下の方のhタグにどの番号を振るべきかで迷いました。

2020-07-24 05:55 UTC, sassamori commented on html-nri/index.html
> +    <nav class="breadcrumbs">
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/1/commits/ba66fd22aeaaa3e9df6eb09e28281b67b2cef4ee

2020-07-24 06:25 UTC, sassamori commented on html-nri/index.html
> +    <title>NRIの強み：ビジネスモデルの特徴</title>
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/1/commits/57f98caa083513fb99dc899a76ba0b559f02c28f

2020-07-24 06:33 UTC, sassamori commented on html-nri/index.html
> +        <nav class="share">
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/1/commits/8cbf20aa428110ed3acf08abe965738a5ae1e15a
https://github.com/sassamori/takaharusasamori/pull/1/commits/313b08767235ee6d93572f71a37f69628926f7d2

2020-07-24 10:35 UTC, n06Ar commented on html-nri/index.html
> +        <section class="underGuideDetail2">
CSSを提出する時に修正をお願いします
class名（変数名にも）を命名する時に数字を使わないようにしてください
class名に数字を使用されると他者が見た時や忘れた頃に見返した時に、数字の意味を推測できないためです

2020-07-24 11:49 UTC, n06Ar requested changes
追加のレビューをしました
ご確認をお願いします

2020-07-24 11:49 UTC, n06Ar commented on html-nri/index.html
> +    <meta property=”og:image” content=”https://www.nri.com/-/media/Corporate/jp/Images/company/whats/story06/story06_img_01.jpg?la=ja-JP&hash=505D40BD561BF25D6D1185858533744FBBE46273” />
画像の直接リンクは避けてローカルに保存して（このリポジトリに画像を置く）使用してください

2020-07-24 11:49 UTC, n06Ar commented on html-nri/index.html
> +    <meta name=”description” content=”株式会社野村総合研究所（NRI）の強みである「デジタルビジネス戦略」について解説しています。”>
レビュー対応で追加した`meta`タグのダブルクォートが異なるので修正をお願いします

現状の`meta`タグのダブルクォート：`”`
他のタグのダブルkウォート：`"`

2020-07-24 13:50 UTC, sassamori commented on html-nri/index.html
> +    <meta name=”description” content=”株式会社野村総合研究所（NRI）の強みである「デジタルビジネス戦略」について解説しています。”>
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/1/commits/90a6574af2c6bb6a92aa76cc385a2a1f650519be
失礼しました。

2020-07-24 14:08 UTC, sassamori commented on html-nri/index.html
> +    <meta property=”og:image” content=”https://www.nri.com/-/media/Corporate/jp/Images/company/whats/story06/story06_img_01.jpg?la=ja-JP&hash=505D40BD561BF25D6D1185858533744FBBE46273” />
理解不足ですいません。
いただいたコメントを元に調べて、画像の直接リンクが好ましくないことがわかりました。
またogp画像は相対パスはNGということも承知しました。
そうなると、画像だけを配置したHTMLファイルをhtml-nriディレクトリに作り、そこの画像URLだけを利用するという解決策になるのでしょうか？

2020-07-24 14:11 UTC, sassamori commented on html-nri/index.html
> +        <section class="underGuideDetail2">
承知しました。
CSSを提出するときに修正いたします。

2020-07-25 01:30 UTC, sassamori commented on html-nri/index.html
> +    <meta property=”og:image” content=”https://www.nri.com/-/media/Corporate/jp/Images/company/whats/story06/story06_img_01.jpg?la=ja-JP&hash=505D40BD561BF25D6D1185858533744FBBE46273” />
完了しました。
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/1/commits/c8847417bf610ccdcdd0af79b48e7e3c9a6f3dd8
間違っていたら、お手数ですがご指摘ください。

2020-07-25 01:53 UTC, n06Ar approved these changes
LGTM!

2020-07-25 02:21 UTC, merged