Feature/html01
sassamori/takaharusasamori pull request #2
Opened 2020-07-31 13:29 UTC by sassamori

NRI課題のCSSを実装しました。

2020-08-01 06:49 UTC, n06Ar requested changes
レビューしました。
コード上の指摘と下記の内容をご確認をお願いいたします。
また、コード上の指摘について類似箇所が何点か見つかったので類似箇所も合わせて修正をお願いいたします。

- リンクの文字がデフォルトの文字色です
- 画面の横幅を1024pxにすると分かりますが、全体的に左よりです

2020-08-01 06:49 UTC, n06Ar commented on html-nri/index.html
> +                    <a href="#"><li>社長メッセージ</li></a>
`ul`タグの直下は、`a`タグ使えないので修正をお願いします
[HTML5 入れ子チートシート](https://yoshikawaweb.com/element/)

2020-08-01 06:49 UTC, n06Ar commented on html-nri/index.html
> +        <a href="#"><img src="images/to_top.png" alt="トップに戻る" width="60px" height="60px"></a>
widthのpxは不要なので削除をお願いいたします
width属性の場合はpxの単位指定は不要です

2020-08-01 06:49 UTC, n06Ar commented on html-nri/index.html
> +                <img src="images/header_image02.jpg" alt="ヘッダー画像" width="1300" height="260">
右側に余白ができているので注意してください
![ヘッダー画像](https://user-images.githubusercontent.com/56122838/89095426-dfee8880-d408-11ea-9a2a-df98c10f5908.png)

2020-08-01 06:49 UTC, n06Ar commented on html-nri/common/style.css
> +.footer .footerAlign{
Alignだと何が並んでいるのか想像しにくいのでフッターのリンクが並んでいることをクラス名に当てると良いです。

2020-08-01 06:49 UTC, n06Ar commented on html-nri/common/style.css
> +.core{
何のcoreかわかりづらいので、クラス名に何のcoreか情報を付与すると良いです

2020-08-01 06:49 UTC, n06Ar commented on html-nri/index.html
> +                        <a href="#"><img src="images/link.png" alt="DXについてのPDF資料" width="300" height="70"></a>
ここは、画像でボタンをつくらず、アイコン以外はテキストベースに修正をお願いします

2020-08-01 06:49 UTC, n06Ar commented on html-nri/common/style.css
> +    background-color: powderblue;
色が異なるのと、色の指定は基本的に`#AAAAAA`などのカラーコードを指定してください

2020-08-01 06:49 UTC, n06Ar commented on html-nri/index.html
> +                    <p>&lt; <a href="#">ビジネスモデルの特徴</a></p>
`&lt;`は装飾なのでCSSで描くようにしてください

2020-08-01 06:49 UTC, n06Ar commented on html-nri/index.html
>      </nav>
HTMLの時に指摘できず申し訳ないのですが、ここから上をmainタグか一部をfooterタグに含むようにしてください。

2020-08-04 05:49 UTC, sassamori commented on html-nri/index.html
> +                    <a href="#"><li>社長メッセージ</li></a>
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/4ea7a5b747af253ef33ea008205daf7db44060c9
よろしくお願い致します。

2020-08-04 05:51 UTC, sassamori commented on html-nri/index.html
> +        <a href="#"><img src="images/to_top.png" alt="トップに戻る" width="60px" height="60px"></a>
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/c0d726ffaaa018505d831a8c84a2ca653ddc4036
よろしくお願い致します。

2020-08-04 05:53 UTC, sassamori commented on html-nri/index.html
> +                <img src="images/header_image02.jpg" alt="ヘッダー画像" width="1300" height="260">
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/4ea7a5b747af253ef33ea008205daf7db44060c9
よろしくお願い致します。

2020-08-04 05:59 UTC, sassamori commented on html-nri/common/style.css
> +.footer .footerAlign{
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/fd89325ba9e84d44136378805610e6f42208bd3e
よろしくお願い致します。

2020-08-04 06:05 UTC, sassamori commented on html-nri/common/style.css
> +.core{
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/4631b9860748d7e97f9717717cf0da37fd1dfa86
よろしくお願い致します。

2020-08-04 07:23 UTC, sassamori commented on html-nri/index.html
> +                        <a href="#"><img src="images/link.png" alt="DXについてのPDF資料" width="300" height="70"></a>
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/840cb0aff2945555e143023d6ea1677bf51989b8
よろしくお願い致します。

2020-08-04 07:28 UTC, sassamori commented on html-nri/common/style.css
> +    background-color: powderblue;
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/1585b8d32b424fc9ae4c333bb49f513786981068
よろしくお願い致します。

2020-08-04 07:43 UTC, sassamori commented on html-nri/index.html
> +                    <p>&lt; <a href="#">ビジネスモデルの特徴</a></p>
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/18a17e154f23cb727b650207ab8a97fe3c00223a
よろしくお願い致します。

2020-08-04 07:58 UTC, sassamori commented on html-nri/common/style.css
> +    background-color: powderblue;
追加のコミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/3c020c51f54376532af19c9b5a0e3603a3f466c6
よろしくお願い致します。

2020-08-04 07:58 UTC, sassamori commented on html-nri/index.html
>      </nav>
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/2452bdf7549eff59ce850fd9fe8b93d98004dddb
よろしくお願い致します。

2020-08-04 12:45 UTC, n06Ar commented on html-nri/index.html
> +            <section class="underGuideDetail" class="noChild">
class属性は一つにしてください
複数クラスを書くときは、スペース区切りで書きます
253行目も同様です

2020-08-04 12:45 UTC, n06Ar commented on html-nri/index.html
> +                <img src="images/header_image02.jpg" alt="ヘッダー画像" width="1440" height="260">
CSSで背景画像を設定されないようでしたので指摘しておきます
ヘッダーの背景画像などは装飾であり文章ではないので、alt属性はなくし、`aria-hidden="true"`をつけてください

2020-08-04 12:45 UTC, n06Ar commented on html-nri/index.html
> +                <img src="images/header_image02.jpg" alt="ヘッダー画像" width="1300" height="260">
こちら再度ご確認をお願いいたします。
確認したところ横幅をpx指定しているため1440pxをブラウザの画面サイズが超えた場合に、右に余白ができるため余白ができないようにしてください。

2020-08-04 12:49 UTC, n06Ar requested changes
追加の指摘を行ました
ご確認をお願いいたします
一つ修正が確認できなかったため[こちらのコメント](https://github.com/sassamori/takaharusasamori/pull/2#discussion_r465022493)のご確認をお願いいたします

2020-08-04 12:49 UTC, n06Ar commented on html-nri/index.html
>          <nav class="breadcrumbs">
パンくずの`&gt;`は装飾なため、CSSで書くようにしてください

2020-08-04 12:56 UTC, n06Ar requested changes

2020-08-04 12:56 UTC, n06Ar commented on html-nri/common/style.css
> +    border: solid 2px gray;
こちらもカラーコードで指定をお願いします

2020-08-04 12:56 UTC, n06Ar commented on html-nri/common/style.css
> +    border-bottom: solid 1px lightsteelblue;
こちらもカラーコードで指定をお願いします

2020-08-04 12:56 UTC, n06Ar commented on html-nri/common/style.css
> +    border-left: solid 1px gray;
こちらもカラーコードで指定をお願いします

2020-08-04 12:56 UTC, n06Ar commented on html-nri/index.html
> +                        <a href="#"><span>デジタルが拓く近未来（NRIのDX）<br>（4.06MB）<img src="images/pdf_icon.png" alt="pdfのアイコン" width="25" height="25"></span></a>
装飾のアイコンは、`alt`属性をなくし`aria-hidden="true"`を設定してください
スクリーンリーダーが不要な文書を読み上げないようにするために設定します

2020-08-05 04:14 UTC, sassamori commented on html-nri/index.html
> +            <section class="underGuideDetail" class="noChild">
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/19286d69a5bdd716be2c31d48e071b435970fdcf
よろしくお願い致します。

2020-08-05 04:18 UTC, sassamori commented on html-nri/index.html
> +                <img src="images/header_image02.jpg" alt="ヘッダー画像" width="1440" height="260">
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/ae48ccc551814b913eda4b5b0af51ca1a1bf007e
よろしくお願い致します。

2020-08-05 04:20 UTC, sassamori commented on html-nri/index.html
> +                <img src="images/header_image02.jpg" alt="ヘッダー画像" width="1300" height="260">
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/80ad40f398ded5040d0a06ef444f0f8b37ade7a0
お手数おかけしてしまい、すいません。

2020-08-05 05:46 UTC, sassamori commented on html-nri/index.html
>          <nav class="breadcrumbs">
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/2686a017bcb7ca7db8992993fa6141265d52dff0
よろしくお願い致します。

2020-08-05 05:50 UTC, sassamori commented on html-nri/common/style.css
> +    border: solid 2px gray;
失礼いたしました。
https://github.com/sassamori/takaharusasamori/pull/2/commits/c76ef472a9fd8329579146709367e0c58033a9bf
よろしくお願い致します。

2020-08-05 05:53 UTC, sassamori commented on html-nri/common/style.css
> +    border-bottom: solid 1px lightsteelblue;
失礼いたしました。
https://github.com/sassamori/takaharusasamori/pull/2/commits/f696b544c32239b4d301e41b56fafb7fd81f9063
よろしくお願い致します。

2020-08-05 05:55 UTC, sassamori commented on html-nri/common/style.css
> +    border-left: solid 1px gray;
失礼いたしました。
https://github.com/sassamori/takaharusasamori/pull/2/commits/135ed237b7b1bab4b279f9e1d293bfc097856398
よろしくお願い致します。

2020-08-05 05:58 UTC, sassamori commented on html-nri/index.html
> +                        <a href="#"><span>デジタルが拓く近未来（NRIのDX）<br>（4.06MB）<img src="images/pdf_icon.png" alt="pdfのアイコン" width="25" height="25"></span></a>
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/358a55b8b90c8910128cd847fab7a9117ff85b35
よろしくお願い致します。

2020-08-05 10:55 UTC, n06Ar requested changes
追加の指摘をしました
お手数ですがご確認をお願いいたします

2020-08-05 10:55 UTC, n06Ar commented on html-nri/index.html
> +                <img src="images/header_image02.jpg" aria-hidden="true" width="100%" height="260">
少し画像のサイズを変更すると、画像が潰れてしまうので潰れないようにしてください
ヒントは`object-fit`です

2020-08-05 10:55 UTC, n06Ar commented on html-nri/index.html
> +                        <a href="#"><span>デジタルが拓く近未来（NRIのDX）<br>（4.06MB）<img src="images/pdf_icon.png" aria-hidden="true" width="25" height="25"></span></a>
`a`タグの装飾（下線）が残っているので修正をお願いします

2020-08-05 10:55 UTC, n06Ar commented on html-nri/index.html
> +                        <a href="#"><span>デジタルが拓く近未来（NRIのDX）<br>（4.06MB）<img src="images/pdf_icon.png" aria-hidden="true" width="25" height="25"></span></a>
ボタンの背景色が異なるので確認をお願いします

2020-08-05 10:55 UTC, n06Ar commented on html-nri/index.html
> +                <nav class="strengthNavi">
元のWebページと背景色が異なります。
ご確認をお願いします。

2020-08-05 12:26 UTC, sassamori commented on html-nri/index.html
> +                <img src="images/header_image02.jpg" aria-hidden="true" width="100%" height="260">
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/41bb02cd044e8acb58624899e9ad9f8b81c2a5be
よろしくお願い致します。

2020-08-05 12:31 UTC, sassamori commented on html-nri/index.html
> +                        <a href="#"><span>デジタルが拓く近未来（NRIのDX）<br>（4.06MB）<img src="images/pdf_icon.png" aria-hidden="true" width="25" height="25"></span></a>
失礼いたしました。
https://github.com/sassamori/takaharusasamori/pull/2/commits/2c92fde6069c7d7022e4518f3f0591006aee8651
よろしくお願い致します。

2020-08-05 12:37 UTC, sassamori commented on html-nri/index.html
> +                        <a href="#"><span>デジタルが拓く近未来（NRIのDX）<br>（4.06MB）<img src="images/pdf_icon.png" aria-hidden="true" width="25" height="25"></span></a>
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/83ac67fe6a38ea59b17f3250a3714a70c4b4c8dd
よろしくお願い致します。

2020-08-05 12:41 UTC, sassamori commented on html-nri/index.html
> +                <nav class="strengthNavi">
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/1cdd1822b4a625f81968bbde44f990c554bfa732
よろしくお願い致します。

2020-08-06 11:24 UTC, n06Ar requested changes
追加の指摘をしました。
一部指摘に見逃しがあったため追加の指摘もしています。申し訳ありません。

また全体的に青文字の`a`タグのリンク色が少し濃いため、そちらも併せて修正をお願いいたします。

2020-08-06 11:24 UTC, n06Ar commented on html-nri/common/style.css
> +    border: solid 1px #000000;
色を薄くしてください
元のページと比較して枠線の色は薄いためご確認をお願いします

2020-08-06 11:24 UTC, n06Ar commented on html-nri/common/style.css
> +    content: '\03e';
このボタンの`>`は、NRIの強みにあるリンクと同じ記号へ修正をお願いします

2020-08-06 12:39 UTC, sassamori commented on html-nri/common/style.css
> +    border: solid 1px #000000;
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/fb28c81041e6ffa2869387bac0b3ba4bc3500d62
よろしくお願い致します。

2020-08-06 13:14 UTC, sassamori commented on html-nri/common/style.css
> +    content: '\03e';
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/2/commits/ea9a85bebd38ea9e9c50dae410872113c9cf8547
よろしくお願い致します。

2020-08-06 15:31 UTC, n06Ar approved these changes
LGTMです！

2020-08-06 15:38 UTC, n06Ar reviewed
imo（in my opinion）的なコメントを追加しました
修正は不要ですが、参考程度に読んでみてください

2020-08-06 15:38 UTC, n06Ar commented on html-nri/index.html
> +            <p><a href="#">NRI トップ</a><a href="#">企業情報</a><a href="#">NRIの強み：NRIのデジタルビジネス戦略</a></p>
パンくずリストなので、`ul`,`li`タグで表記することが多いです

2020-08-06 15:38 UTC, n06Ar commented on html-nri/index.html
> +                    <table>
`NRIの強み`の一覧とも取れるので`ul`,`li`タグでリストとしてhtmlを書き、CSSで`display:table`や`flexbox`でデザインを書いたりします

2020-08-07 08:47 UTC, merged