Feature/html01
sassamori/takaharusasamori pull request #3
Opened 2020-08-11 08:02 UTC by sassamori

N高課題のHTMLを作成しました。

2020-08-11 12:14 UTC, n06Ar requested changes
レビューしました
ご確認の程をお願いいたします

2020-08-11 12:14 UTC, n06Ar commented on html-nkou/index.html
> +    <meta charset="utf-8">
`description`や`keywords`、OGP系のmetaタグがないので追加してください

2020-08-11 12:14 UTC, n06Ar commented on html-nkou/index.html
> +                                <img src="images/footer05_nlabo.png" alt="N高中等部ロゴ" width="150" height="50">
この画像は、N中等部の画像ではなかったので気をつけてください

2020-08-11 12:14 UTC, n06Ar commented on html-nkou/index.html
> +            <h5>KADOKAWAが創る新しいネットの高校</h5>
`h1,2,3,4`がなく`h5`から始まっています
基本的に`h1`から始めるようにしてください
文書的に大見出しなしの小見出しから始まるのは違和感があります

2020-08-11 12:34 UTC, n06Ar reviewed
imo(in my opinion)なコメントを追記しました
修正は必須ではないので参考に読んでみてください

2020-08-11 12:34 UTC, n06Ar commented on html-nkou/index.html
> +                            <li><span>教　養</span>自分なりの考えをもつための知識</li>
単語に対する説明の場合は、`dd`,`dt`,`dl`タグを使用します

2020-08-11 12:34 UTC, n06Ar commented on html-nkou/index.html
> +                    <img src="images/campus_photo_01.jpg" aria-hidden="true" width="100%" height="600">
imgタグでは、`width`や`height`属性の内容は基本的にcssに記述します
レスポンシブデザインに適用するためには、HTMLて定義するよりCSSで行う方が良いためです（装飾の話なので
ただし、画像の読み込みの遅延対策で`width`や`height`属性を使用することもあります

2020-08-11 12:34 UTC, n06Ar commented on html-nkou/index.html
> +                            <img src="images/about_img02_01_20170927.png" alt="N高生の1日例" width="420" height="500">
画像で伝えたいことは、自分がやりたい勉強の時間が多いことなので、alt属性にそのことも追記すると良いです

2020-08-11 12:34 UTC, n06Ar commented on html-nkou/index.html
> +                                <img src="images/about_img02_02.png" alt="将来へ繋がる多くの経験" width="450" height="350">
SEO対策的には、プログラミングやイラストレーター、小説家などの経験ができることを書くと良いです
ただし、キーワードの羅列は逆にSEO的にマイナスなので気をつけてください。

2020-08-11 12:34 UTC, n06Ar commented on html-nkou/index.html
> +                            <img src="images/about_img05_01.jpg" alt="先端企業が使用するITツール" width="680" height="480">
先端企業が使用するslackやGitHubなどのITツールでも良いと思います

2020-08-11 12:34 UTC, n06Ar commented on html-nkou/index.html
> +                            <img src="images/about_img09_04.jpg" alt="提携スクールの例" width="680" height="480">
SEOやスクリーンリーダーを使用しているユーザ的に一部の提携スクールの名前をalt属性に入れても良いと思います

2020-08-11 22:30 UTC, sassamori commented on html-nkou/index.html
> +    <meta charset="utf-8">
失礼いたしました。
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/3/commits/c04ee1d7bfc692cf8f3adc42a798fb7cf01dcbda
よろしくお願い致します。

2020-08-11 22:33 UTC, sassamori commented on html-nkou/index.html
> +                                <img src="images/footer05_nlabo.png" alt="N高中等部ロゴ" width="150" height="50">
失礼いたしました。
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/3/commits/cbf0ac61361f0a616e7656aa16a62d459eead241
よろしくお願い致します。

2020-08-11 22:38 UTC, sassamori commented on html-nkou/index.html
> +            <h5>KADOKAWAが創る新しいネットの高校</h5>
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/3/commits/ad3a599036b25f2c40a45faf08e9e8fcfed1ead6
よろしくお願い致します。

2020-08-11 22:45 UTC, sassamori commented on html-nkou/index.html
> +                            <li><span>教　養</span>自分なりの考えをもつための知識</li>
ありがとうございます。
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/3/commits/877be61180e52617a7c58f2778e8c0feaae8da0e
よろしくお願い致します。

2020-08-11 22:49 UTC, sassamori commented on html-nkou/index.html
> +                            <img src="images/about_img02_01_20170927.png" alt="N高生の1日例" width="420" height="500">
ありがとうございます。
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/3/commits/2849eced6a7141f1450af1daa6885a1ee3602f73
よろしくお願い致します。

2020-08-11 22:52 UTC, sassamori commented on html-nkou/index.html
> +                                <img src="images/about_img02_02.png" alt="将来へ繋がる多くの経験" width="450" height="350">
ありがとうございます。
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/3/commits/51590fd6f82245b7a79cbef7a6bea5eef5631449
よろしくお願い致します。

2020-08-11 22:54 UTC, sassamori commented on html-nkou/index.html
> +                            <img src="images/about_img05_01.jpg" alt="先端企業が使用するITツール" width="680" height="480">
ありがとうございます。
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/3/commits/a23f2b3d9c229d8a4fdbddc9bf1f0ac181ab3302
よろしくお願い致します。

2020-08-11 23:00 UTC, sassamori commented on html-nkou/index.html
> +                            <img src="images/about_img09_04.jpg" alt="提携スクールの例" width="680" height="480">
ありがとうございます。
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/3/commits/1efc491c6ef3a39eeabb8bb2ad28d6483e05322f
よろしくお願い致します。

2020-08-11 23:01 UTC, sassamori commented on html-nkou/index.html
> +                    <img src="images/campus_photo_01.jpg" aria-hidden="true" width="100%" height="600">
ありがとうございます。
CSSの時に余裕があったら考えてみます。

2020-08-12 20:32 UTC, n06Ar approved these changes
LGTMです！

2020-08-13 02:17 UTC, merged