Feature/html01
sassamori/takaharusasamori pull request #4
Opened 2020-08-18 08:11 UTC by sassamori

N高課題のCSSを作成しました。

2020-08-18 16:10 UTC, n06Ar requested changes
レビューしました
ご確認をお願いします

また、全体的な指摘として下記があります
- CSSのセレクタが冗長なケースがある
  - 例えば`aboutSubContentsParallelRight`クラスのレベルで詳細な命名をするのであれば`.articleMain`と` .aboutSub`はなくても競合する可能性は低いのでこの二つのクラスは不要になります
- paddingとmarginのpx指定は避けた方が良いです
  - 現在では、PCの画面は何種類かあるのでパーフェクトピクセルなデザインは不可能です。そのため、少し画面サイズを変更してレイアウトが崩れないか確認してみてください（画面サイズが1440ぐらいであれば±100pxぐらいで見ると良いかと思います）
    - 今回はレスポンシブデザインの課題ではないのでスマートフォンの画面サイズの確認は不要です

追記
- Safariだと明朝体になっていたのでフォントの確認をお願いします

2020-08-18 16:10 UTC, n06Ar commented on html-nkou/index.html
> +                                    <span></span><img src="images/text_read_more01_black01.png" alt="read more" width="80" height="15">
空の`span`タグがありますがこちらの意図は何でしょうか？

2020-08-18 16:10 UTC, n06Ar commented on html-nkou/common/style.css
> +    width: 74%;
長さが足りないため右側が空いています
![長さが足りないため右側に空白がある](https://user-images.githubusercontent.com/56122838/90534646-f2acdf80-e1b4-11ea-81d7-8529ccc0ab0f.png)

2020-08-18 16:10 UTC, n06Ar commented on html-nkou/index.html
> +                                <div class="readMore">
全体的にRead Moreと`>`の記号が少し大きいので調整をお願いします
![ReadMore](https://user-images.githubusercontent.com/56122838/90536095-92b73880-e1b6-11ea-9738-1fbd27f31325.png)

2020-08-18 16:10 UTC, n06Ar commented on html-nkou/common/style.css
> +    top: 10px;
ピクセル指定なので、ブラウザの画面サイズが1980pxの横幅ではレイアウトが崩れます
![Screen Shot 2020-08-19 at 0 58 18](https://user-images.githubusercontent.com/56122838/90536511-1b35d900-e1b7-11ea-832d-5d739fbe53ea.png)

2020-08-18 16:21 UTC, n06Ar approved these changes
実はこの課題では、JavaScriptの実装は不要でしたが、実装されていたのでコメントだけしておきました。
PHPの時に意識することも書いてあるので読んでみてください
修正は不要です

2020-08-18 16:21 UTC, n06Ar commented on html-nkou/index.html
> +            var flag = "view";
`var`の使用は避けた方が良いです。この場合は再代入ができる`let`を使用した方が良いです。
`var`はスコープの懸念や多重宣言、宣言の巻き上げの問題があります

2020-08-18 16:21 UTC, n06Ar commented on html-nkou/index.html
> +            var flag = "view";
`flag`と言う命名で文字列が入るのは避けた方が良いです
この場合なら`status`などの方が良いです
`flag`と言うと通常`true` or `false`がデファクトスタンダードになっており、他の人が実装した時に混乱するので避けるべきです

2020-08-19 06:42 UTC, sassamori commented on html-nkou/index.html
> +                                    <span></span><img src="images/text_read_more01_black01.png" alt="read more" width="80" height="15">
ご指摘ありがとうございました。
上記の全体的な指摘について、ここで返信させていただきます。
※直し方で不備があれば、再度ご指摘いただけると助かります。

◎「CSSのセレクタが冗長なケースがある」について
articleMainは不要だったので、削りました。
代わりにaboutMainをarticleタグにしました。
aboutSubについてはaboutMainとの差別化の意味で残しています。
https://github.com/sassamori/takaharusasamori/pull/4/commits/32fe653bcc36024a285be5551ffe97f95149de93

◎paddingとmarginのpx指定は避けた方が良いです
paddingで中央寄せしていたものについて、全てmargin: 0 auto;とwidth: ●●px;で中央寄せしました。

2020-08-19 06:47 UTC, sassamori commented on html-nkou/index.html
> +                                    <span></span><img src="images/text_read_more01_black01.png" alt="read more" width="80" height="15">
＞空のspanタグがありますがこちらの意図は何でしょうか？
こちらのspanタグで記号「＞」を作り出しています。
※セレクタでクラス名の.readMoreが入っていないものがありましたので、わかりにくかったと思います。すいません。
https://github.com/sassamori/takaharusasamori/pull/4/commits/fccb83d9d16d32225048ab42c0990aa8d6200b32

2020-08-19 06:49 UTC, sassamori commented on html-nkou/common/style.css
> +    width: 74%;
修正いたしました。
https://github.com/sassamori/takaharusasamori/pull/4/commits/b203785193732645a38f3bce84980f73298cb199
よろしくお願い致します。

2020-08-19 06:59 UTC, sassamori commented on html-nkou/index.html
> +                                <div class="readMore">
修正いたしました。
https://github.com/sassamori/takaharusasamori/pull/4/commits/bda4ae6a08e11c54601243fde0e568d9e600d8fe
よろしくお願い致します。

2020-08-19 07:03 UTC, sassamori commented on html-nkou/common/style.css
> +    top: 10px;
修正いたしました。
https://github.com/sassamori/takaharusasamori/pull/4/commits/9c5f607363229f0ec087104533a9855481a84820
上記のコミットの途中で修正しています。

2020-08-19 07:04 UTC, sassamori commented on html-nkou/index.html
> +            var flag = "view";
ありがとうございます！

2020-08-19 07:04 UTC, sassamori commented on html-nkou/index.html
> +            var flag = "view";
ありがとうございます！

2020-08-19 15:17 UTC, n06Ar commented on html-nkou/common/style.css
> +    top: 10px;
こちらで確認してみたら3~4%追加しても良さそうでした

2020-08-19 15:20 UTC, n06Ar commented on html-nkou/index.html
> +                                    <span></span><img src="images/text_read_more01_black01.png" alt="read more" width="80" height="15">
> こちらのspanタグで記号「＞」を作り出しています。
この場合はクラスを使った方が良いです
命名はお任せしますが、`icon`とかをつけると何かしらの記号を使っていることが伝わるのでhtml上からでもCSSの装飾が想像できます

2020-08-20 00:31 UTC, sassamori commented on html-nkou/index.html
> +                                    <span></span><img src="images/text_read_more01_black01.png" alt="read more" width="80" height="15">
なるほどです。
修正いたしました。
https://github.com/sassamori/takaharusasamori/pull/4/commits/f162b9e1a09dcd67f30c97628ad934cb82c13c9b
よろしくお願い致します。

2020-08-20 00:43 UTC, sassamori commented on html-nkou/common/style.css
> +    top: 10px;
ありがとうございます。
.aboutMainHeadTextのleftの値を少しいじりました。
自分のPCでは3%追加（+）するとズレるようだったので、2%削減（-）しています。
https://github.com/sassamori/takaharusasamori/pull/4/commits/29c68fa2739ccebe30f9eb52dea05722675b74d7

2020-08-20 15:40 UTC, n06Ar commented on html-nkou/common/style.css
> +    top: 10px;
色々と調整していただいたところ申し訳ないです
leftのみで中央よせは（画面サイズ的に）無理そうなので下記のrightも指定するで対応をお願いします
```css
.aboutMain .aboutMainHead .aboutMainHeadText {
    position: absolute;
    top: 10px;
    left: 0;
    right: 0;
    text-align: center;
}
```

2020-08-21 00:37 UTC, sassamori commented on html-nkou/common/style.css
> +    top: 10px;
こんな技があったんですね…ありがとうございます。
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/4/commits/42168282093357f3c8adf85c8498529c6ffcaefd
よろしくお願い致します。

2020-08-21 01:10 UTC, ykyk1218 commented
通りすがりです。

このあたりの aタグに `position: absolute` を使っているのが気になりました。
`position: absolute` を使うこと自体は悪いことではないですが、`position: absolute` はレイアウトの変更（今後サイトを運用していくに当たってテキストを変更したり画像を追加したりなど）に弱いので、極力使わない方がいいかなと思っています。
特にここは必要ないのでは...と思ったのでコメントです。

<img width="1142" alt="N高について｜N高等学校" src="https://user-images.githubusercontent.com/830861/90840795-f6e42300-e395-11ea-8796-7c058ee53254.png">

2020-08-21 02:38 UTC, sassamori commented
小林さん

ありがとうございます。
修正しました。
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/4/commits/90449fa884c8485924c3929d785b9c900b9fc69e

absoluteがレイアウト変更を阻害することは知りませんでした。
ググったのですが「relativeと一緒ならOK」という情報にしかたどり着けなかったので、この件について説明がまとまっているサイトのURLがあれば教えていただきたいです。

2020-08-22 00:28 UTC, n06Ar commented
> absoluteがレイアウト変更を阻害することは知りませんでした。
> ググったのですが「relativeと一緒ならOK」という情報にしかたどり着けなかったので、この件について説明がまとまっているサイトのURLがあれば教えていただきたいです。

この件は、[MDNのposition](https://developer.mozilla.org/ja/docs/Web/CSS/position)を頑張って読み取るとわかりますがコンテンツの高さや横幅が取られないことや、`top`や`left`を書くと`positionを持つ`祖先のタグ要素を探索し（htmlタグまで）それを基準に位置づけをしたりするので、親のタグのスタイルに依存するためレイアウト変更する時に影響範囲が広がる可能性があります

2020-08-22 00:40 UTC, ykyk1218 commented
適当なサンプルを作ってみました。
見出しがあって、その下にボタンがあるようなレイアウトです。
ボタンを `position: absolute;` で配置しています。
![image](https://user-images.githubusercontent.com/830861/90944662-358fe100-e45b-11ea-842c-49af4f734827.png)


```html
<html>
  <head>
    <style type="text/css">
      #box1 {
        width: 200px;
        height: 200px;
        border: 1px solid #ddd;
        position: relative;
      }

      #box1 p {
        padding-left: 5px;
        padding-top: 5px;
      }

      #box1 button {
        position: absolute;
        top: 50px;
        left: 50px;
      }
    </style>
  </head>
  <body>
     <div id="box1">
        <p>サンプル見出し</p>
       <button>ボタン1</button>
     </div>
  </body>
</html>
```

この場合に、見出しの下に追加で何かテキストを入れるとテキストがボタンに被ってしまいます。
これを直すには `top: 50px;` の調整をしないといけないのですが、これを変更のたびにやるのは辛いのでなるべく使わない方がいいということですね 😄

2020-08-22 00:57 UTC, sassamori commented
のぶさん
サイトのURLとご説明、ありがとうございます。

小林さん
わかりやすい図説、ありがとうございます。

absoluteは便利だからと言って頻繁に用いることはやめようと思います！

2020-08-22 02:44 UTC, n06Ar requested changes
追加でレビューしました
たびたび申し訳ないですがご確認をお願いいたします

2020-08-22 02:44 UTC, n06Ar commented on html-nkou/index.html
> +                    </div>
ここの`div`タグの閉じるは下にもあるので不要です

2020-08-22 02:44 UTC, n06Ar commented on html-nkou/common/style.css
> +    margin: 0 auto;
`marign`はなくても問題ないです

2020-08-22 02:44 UTC, n06Ar commented on html-nkou/common/style.css
> +.globalNavi .globalNaviMajor .globalNaviMajorRight p a:hover:before{
一部スタイルが314行目のものと重複しているので一部は削除して良いです

2020-08-22 02:55 UTC, n06Ar reviewed
動作上は問題がない細かいコメントをしました
ご確認いただければと思います

2020-08-22 02:55 UTC, n06Ar commented on html-nkou/common/style.css
> +    margin: 0 auto;
margin-topとmargin-bottomをまとめて、`margin:20px 0 auto auto`にしても良いと思いました

2020-08-22 02:55 UTC, n06Ar commented on html-nkou/common/style.css
> +    background-image: repeating-linear-gradient(51deg, transparent, transparent 3px, rgba(227, 225, 225, 1) 3px, rgba(227, 225, 225, 1) 4px );    padding: 30px;
paddigが二つありますが後者が使われているのであれば1243行目のpaddigを消してください

2020-08-22 08:35 UTC, sassamori commented on html-nkou/index.html
> +                    </div>
失礼いたしました。
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/4/commits/c7f71f09b896ff2d67076534780f3efb56fb4681
よろしくお願い致します。

2020-08-22 08:37 UTC, sassamori commented on html-nkou/common/style.css
> +    margin: 0 auto;
ありがとうございます。
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/4/commits/d43bef14dd2179b137582122cd781e20b84283d0
よろしくお願い致します。

2020-08-22 08:48 UTC, sassamori commented on html-nkou/common/style.css
> +.globalNavi .globalNaviMajor .globalNaviMajorRight p a:hover:before{
ありがとうございます。
無駄に書いていました…。
該当箇所は:hoverしてるところですよね。
https://github.com/sassamori/takaharusasamori/pull/4/commits/f792362f311dcc958019461fcd2f6a46f686e094
よろしくお願い致します。

2020-08-22 08:55 UTC, sassamori commented on html-nkou/common/style.css
> +    margin: 0 auto;
失礼いたしました。
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/4/commits/c57b724814bef5d5654fdaef63dfcb17f344e0d9
よろしくお願い致します。

2020-08-22 08:58 UTC, sassamori commented on html-nkou/common/style.css
> +    background-image: repeating-linear-gradient(51deg, transparent, transparent 3px, rgba(227, 225, 225, 1) 3px, rgba(227, 225, 225, 1) 4px );    padding: 30px;
ありがとうございます。
コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/4/commits/f49ac8698da270ca5e000808d3046e11004095a4
よろしくお願い致します。

2020-08-22 11:40 UTC, n06Ar approved these changes
LGTMです！

2020-08-22 12:25 UTC, merged