Feature/php01
sassamori/takaharusasamori pull request #5
Opened 2020-10-01 11:02 UTC by sassamori

2020-10-03 14:12 UTC, n06Ar requested changes
今回の課題に関連するコードに限って、コードレビューをしました。
動作確認によるレビューは、コードレビュー後に実施します。

PHPで削除フラグによる条件を使われていますが、この実装は避けてください。
論理削除されたレコードは、メンテナンス画面を除き取得しないください。
そもそも論理削除されたレコードは、既に実態がないはず（物理削除されているはず）のレコードであり、問題の調査や履歴データとしての用途としてしか使われないものなためです。

2020-10-03 14:12 UTC, n06Ar commented on php-rt-iine/post/dbconnect.php
> +?>
phpの処理しかないファイルでは、phpの終了タグを絶対書かないようにしてください。
終了タグの後に空行や半角スペースがあるとhtmlと認識して想定外の改行が含まれる可能性があるためです。

2020-10-03 14:12 UTC, n06Ar commented on php-rt-iine/post/index.php
> +        header('Location: index.php');
ここで`index.php`にリダイレクトしていますが、後続の処理が画面に表示するデータを取得する処理のためリダイレクトは不要です。

2020-10-03 14:12 UTC, n06Ar commented on php-rt-iine/post/index.php
> +$page = $_REQUEST['page'];
32から34行目までの処理は合体演算子を使うことで1行で済ますことができます。

2020-10-03 14:12 UTC, n06Ar commented on php-rt-iine/post/index.php
> +    if($_POST['message'] != ''){
`!=`だと厳密な比較ができないため0も`''`と同じ扱いになります。
そのため、`!==`を使う必要があります。

2020-10-03 14:12 UTC, n06Ar commented on php-rt-iine/post/index.php
> +$counts = $db->query('SELECT COUNT(*) AS cnt FROM posts');
データの取得条件に`delete_flag`がありませんが、論理削除した投稿もカウントする実装が正で問題ないでしょうか？
他のコードで論理削除をしているように見受けられたので、確認したい次第です。

2020-10-03 14:12 UTC, n06Ar commented on php-rt-iine/post/index.php
> +    WHERE NOT (rt_flag=1 AND delete_flag=1) ORDER BY posts.created DESC LIMIT ?,5'
この条件だと`rt_flag`が0または、`delete_flag`が0の条件となり、一部の`delete_flag`が0であるレコードが含まれますが問題ないでしょうか？

2020-10-03 14:12 UTC, n06Ar commented on php-rt-iine/post/index.php
> +    $rt_counts = $db->prepare('SELECT COUNT(*) as cnt FROM rts WHERE rt_delete_flag=0 AND post_id=?');
DBからデータを取得するロジックは、画面を表示する処理上で書かないようにしてください。
表示用の処理と取得用の処理は分離するようにしてください。
いろんな責務を持ったロジックが混在すると修正するときに、他の人がコードを読んだ時にコードがロジックを探しづらくなります。

2020-10-03 14:12 UTC, n06Ar commented on php-rt-iine/post/index.php
> +    $member = $members->fetch();
`$member`の変数の命名からは、ログインしている本人のアカウントを取得結果であることがロジック見ないとわからないのです。そのため、この命名は避けてください。

2020-10-03 14:12 UTC, n06Ar commented on php-rt-iine/post/index.php
> +    $members = $db->prepare('SELECT * FROM members WHERE id=?');
`$members`となっていますが、これはログインしている本人のアカウント情報を取得するPrepared Statementの情報を持った変数と考えると命名とは違った意味合いを持っているので、このような命名は避けるようにしてください。

2020-10-03 14:12 UTC, n06Ar commented on php-rt-iine/post/index.php
> +            <?php if($post['id'] == $favo['post_id'] && $member['id'] == $favo['pushing_member_id'] && $favo['delete_flag'] == 0): ?>
delete_flagが1ではないレコードは、取得段階（SQL）の条件に含めるようにしてください。
ここの条件では、`delete_flag`が0なfavosテーブルのレコードの存在の有無を条件にすれば解決できます。

2020-10-03 14:12 UTC, n06Ar commented on php-rt-iine/post/index.php
> +        foreach($favos_all as $favo):
このロジックだと最悪、favosテーブルのデータ全てを検査する非常に重たい処理になります。
131行目で`delete_flag`の内容も取得してきている様子が見られることから、favosテーブルのレコード数が膨大になった場合にメモリ足りずクラッシュする可能性を考慮する必要が出てきます。
そのため、postsテーブルの1投稿に対して関連するfavosテーブルの内容を取得する処理にするようにした方が良いです。

2020-10-03 14:12 UTC, n06Ar commented on php-rt-iine/post/index.php
> +function h($value){
この`h`関数のような共通で使いまわすことができそうな関数は、共通処理として別の`.php`ファイルに分離し、各`php`ファイルから`require_once`で読み込むようにすると良いです。

2020-10-03 14:12 UTC, n06Ar commented on php-rt-iine/post/index.php
> +require('dbconnect.php');
基本的に、require_oneceを使うようにしてください。
requireは多重で読み込みを行うリスクがあります。

2020-10-05 11:57 UTC, sassamori commented on php-rt-iine/post/index.php
> +        header('Location: index.php');
すいません、こちらは教科書p268では「重複投稿を防ぐ仕組み」となっています。
そのような仕組みは不要、もしくはもっと下部で行おうということでしょうか？

2020-10-06 11:07 UTC, sassamori commented on php-rt-iine/post/dbconnect.php
> +?>
修正コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/5/commits/6171ef06c6242141a3a9ebe69fb26697a5448d32
ご確認よろしくお願いいたします。

2020-10-06 11:19 UTC, sassamori commented on php-rt-iine/post/index.php
> +$page = $_REQUEST['page'];
修正コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/5/commits/2f78016a229ad3a07a3df2b4eeb4cd60783865a6
ご確認よろしくお願い致します。

2020-10-06 11:22 UTC, sassamori commented on php-rt-iine/post/index.php
> +    if($_POST['message'] != ''){
修正コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/5/commits/7bff644805e443f8ce1dccfb7a89c4037e9de62d
ご確認よろしくお願い致します。

2020-10-06 11:37 UTC, sassamori commented on php-rt-iine/post/index.php
> +$counts = $db->query('SELECT COUNT(*) AS cnt FROM posts');
ご指摘の通り、間違っておりました。
修正コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/5/commits/d3908d66007990ecd403fd1fa582ab655d934858
ご確認よろしくお願い致します。

WHERE句がNOT（）云々になっていて違和感あると思いますが、現状のDBではこれが正となります。
自分で作ったDB、とてもわかりづらいですね。

2020-10-06 11:42 UTC, sassamori commented on php-rt-iine/post/index.php
> +    $members = $db->prepare('SELECT * FROM members WHERE id=?');
修正コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/5/commits/22b2b6b509cee76efc26ff4e43ba820d3bfe3f19
ご確認よろしくお願い致します。

2020-10-06 11:48 UTC, sassamori commented on php-rt-iine/post/index.php
> +require('dbconnect.php');
修正コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/5/commits/57c598be9075518e62f921ea77ce61fbec40d783
ご確認よろしくお願い致します。

2020-10-06 11:53 UTC, sassamori commented on php-rt-iine/post/index.php
> +function h($value){
hファンクションに関する修正コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/5/commits/fb1c801d55eb843f32cc031a187f26dd2b4cce8f
ご確認よろしくお願い致します。

2020-10-06 11:56 UTC, sassamori commented on php-rt-iine/post/index.php
> +function h($value){
makelinkファンクションに関する修正コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/5/commits/af11ad0e3eb8e29362504cd91891414e97dff4e6
ご確認よろしくお願い致します。

2020-10-07 07:25 UTC, sassamori commented on php-rt-iine/post/index.php
> +            <?php if($post['id'] == $favo['post_id'] && $member['id'] == $favo['pushing_member_id'] && $favo['delete_flag'] == 0): ?>
修正コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/5/commits/43b8ecba5e2bfa0bc5fac85366677b88865ee380
https://github.com/sassamori/takaharusasamori/pull/5/commits/9e8e5f02b7a2946e3ade4562e51f1cd4ac35481c
ご確認よろしくお願い致します。

2020-10-07 08:11 UTC, sassamori commented on php-rt-iine/post/index.php
> +            <?php if($post['id'] == $favo['post_id'] && $member['id'] == $favo['pushing_member_id'] && $favo['delete_flag'] == 0): ?>
上記では動作が上手くいかなかったので、以下を加えてコミットしました。
https://github.com/sassamori/takaharusasamori/pull/5/commits/14839f4732c2483ae4fb6d77851da5321bebefe9
よろしくお願い致します。

2020-10-07 08:13 UTC, sassamori commented on php-rt-iine/post/index.php
> +        foreach($favos_all as $favo):
1つ上のコメントのやり取りにて解決したと思われます。
よろしくお願い致します。

2020-10-07 08:57 UTC, sassamori commented on php-rt-iine/post/index.php
> +    WHERE NOT (rt_flag=1 AND delete_flag=1) ORDER BY posts.created DESC LIMIT ?,5'
一旦、仕様としては問題ないです。
delete_flag=1でもrt_flag=0であれば、表示させる仕様です。
元々delete_flagはrt_delete_flagだったのですが、他テーブルの同名カラムがあったことから改称してしまいました。

ただ非常にわかりづらいですね。
継ぎ足しで作っていたことから、こんなかんじになってしまいました…。

2020-10-07 09:00 UTC, sassamori commented on php-rt-iine/post/index.php
> +    $member = $members->fetch();
修正コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/5/commits/892750883589c8bfb623cbb199e1ea2a10b7218b
ご確認よろしくお願い致します。

2020-10-07 09:04 UTC, sassamori commented on php-rt-iine/post/index.php
> +    $rt_counts = $db->prepare('SELECT COUNT(*) as cnt FROM rts WHERE rt_delete_flag=0 AND post_id=?');
ここの解決方法がわかりませんでした。
あくまで$postsによるforeachの中でデータ取得しなければならないと思うのですが、ここ以外で行うやり方が思いつきませんでした。
ヒントをいただけますでしょうか。

暫定で$favo_judgmentというデータ取得も似たようなやり方で取得してしまっていますので、ヒントをいただいたら順次修正させていただきます。

2020-10-08 08:32 UTC, n06Ar commented on php-rt-iine/post/index.php
> +        header('Location: index.php');
理由があるのであれば現状で問題ないです。

2020-10-08 08:56 UTC, n06Ar commented on php-rt-iine/post/index.php
> +    $rt_counts = $db->prepare('SELECT COUNT(*) as cnt FROM rts WHERE rt_delete_flag=0 AND post_id=?');
> DBからデータを取得するロジックは、画面を表示する処理上で書かないようにしてください。

詳細に書くと、このPHPファイルの上部には、submitされたデータを扱うロジックとデータベースにアクセスするロジックがありますが、そちらに寄せるという意味合いです。

> あくまで$postsによるforeachの中でデータ取得しなければならないと思うのですが、ここ以外で行うやり方が思いつきませんでした。

完結に言うと、$postsに関連した配列を作り対応すると良いです。
流れ的に言うと下記の流れです。

1. $postsのデータを取得
2. $postsでforeachし、$rt_countsのようなデータを取得し$postsに紐づく配列を作る
3. この行でもforeachし、$postsとデータが入った配列を使う

2020-10-08 11:37 UTC, n06Ar requested changes
追加のレビューしました。
ご確認をお願いします。

修正の有無はお任せしますが、`function_h.php`と`function_makelink.php`と関数ごとにファイルを分けていただきましたが、`function_common.php`として共通処理が入ったPHPファイルとして分けると良いです。
functionレベルで、ファイルを分けるとファイルの数が多くなるため、ある程度のグルーピングをすると良いです。

2020-10-08 11:37 UTC, n06Ar commented on php-rt-iine/post/index.php
> +$page = $_GET['page'];
下の行で合体演算子を使われているので、この行での代入は不要です。

2020-10-08 11:37 UTC, n06Ar commented on php-rt-iine/post/index.php
> +    WHERE NOT (rt_flag=1 AND delete_flag=1) ORDER BY posts.created DESC LIMIT ?,5'
承知しました。取り急ぎ、この辺りの処理は動作確認のレビューにて確認させていただきます。

2020-10-08 11:37 UTC, n06Ar commented on php-rt-iine/post/delete.php
> +?>
終了タグがあります。他のPHPファイルでも同様のことが起きているので確認をお願いします。

2020-10-09 11:15 UTC, sassamori commented on php-rt-iine/post/index.php
> +        header('Location: index.php');
承知しました！

2020-10-09 11:42 UTC, sassamori commented on php-rt-iine/post/index.php
> +    $rt_counts = $db->prepare('SELECT COUNT(*) as cnt FROM rts WHERE rt_delete_flag=0 AND post_id=?');
すいません、理解力が足りず「$postsに関連した配列」の具体的イメージができませんでした。
言い換えると、$postsと配列を関連づける方法がわかりませんでした。
キーにpost_id、バリューにrt_countを入れた連想配列を作るかんじでしょうか…？

申し訳ないですが、明日、口頭で質問させてください。

2020-10-09 11:50 UTC, sassamori commented on php-rt-iine/post/index.php
> +$page = $_GET['page'];
失礼いたしました。
修正コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/5/commits/fcaadc495b40890aade79d45dea6e2d837bacc92
ご確認よろしくお願い致します。

2020-10-09 11:58 UTC, sassamori commented on php-rt-iine/post/delete.php
> +?>
失礼いたしました。
修正コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/5/commits/203306d447360565ca9a4d28e8e70f21f81eecbe
ご確認よろしくお願い致します。

2020-10-10 07:34 UTC, sassamori commented on php-rt-iine/post/index.php
> +    $rt_counts = $db->prepare('SELECT COUNT(*) as cnt FROM rts WHERE rt_delete_flag=0 AND post_id=?');
先ほどはありがとうございます。
修正コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/5/commits/125d4e59d426377b7e62dbb2ff736201301e9fbd
続いてfavoの方も修正します。

2020-10-10 07:55 UTC, sassamori commented on php-rt-iine/post/index.php
> +    $rt_counts = $db->prepare('SELECT COUNT(*) as cnt FROM rts WHERE rt_delete_flag=0 AND post_id=?');
favoに関しても修正いたしました。
https://github.com/sassamori/takaharusasamori/pull/5/commits/a97291ee7460c99d4524a7343ad44f73993b2c23
ご確認よろしくお願い致します。

2020-10-11 05:29 UTC, ykyk1218 commented on php-rt-iine/memo/index.php
> +<?php require_once('dbconnect.php'); ?>
全体的にですが、html にインデントが欲しいですね ☺️ 
その方が見通しが良くなる気がします

2020-10-11 05:29 UTC, ykyk1218 commented on php-rt-iine/memo/input_do.php
> +$statement = $db->prepare('INSERT INTO memos SET memo=?,created_at=NOW()');
このsqlエラーになる予感がします😣🙄

2020-10-11 05:29 UTC, ykyk1218 commented on php-rt-iine/post/favo.php
> +    $favo = $db->prepare('INSERT INTO favos SET post_id=?,pushing_member_id=?,delete_flag=0,created=NOW()');
このsqlはエラーになる予感🥺😩😫

2020-10-11 05:29 UTC, ykyk1218 commented on php-rt-iine/post/favo_cancel.php
> +if(isset($_GET['id']) && isset($_SESSION['id'])){
ここ$_SESSION[id]があるかどうかしかみてないのでほかのユーザーのfavoもそうさできちゃいそうです👻

2020-10-11 05:29 UTC, ykyk1218 commented on php-rt-iine/post/index.php
> +        $message = $db->prepare('INSERT INTO posts SET member_id=?,message=?,reply_post_id=?,created=NOW()');
エラーになりそうな予感…

2020-10-12 08:31 UTC, sassamori commented on php-rt-iine/memo/index.php
> +<?php require_once('dbconnect.php'); ?>
どう直したらいいかがググってもわからなかったので、今度リーダブルコードを読みます。

2020-10-12 08:48 UTC, sassamori commented on php-rt-iine/memo/input_do.php
> +$statement = $db->prepare('INSERT INTO memos SET memo=?,created_at=NOW()');
こちらのファイルは課題の範囲外です。
また教科書から書き写したSQL文です。
自分の環境ではエラーなく動作しています…。

2020-10-12 08:51 UTC, sassamori commented on php-rt-iine/post/favo.php
> +    $favo = $db->prepare('INSERT INTO favos SET post_id=?,pushing_member_id=?,delete_flag=0,created=NOW()');
自分の環境ではエラーなく動作しています…。

2020-10-12 08:53 UTC, sassamori commented on php-rt-iine/post/index.php
> +        $message = $db->prepare('INSERT INTO posts SET member_id=?,message=?,reply_post_id=?,created=NOW()');
自分の環境ではエラーなく動作しています…。

2020-10-12 09:25 UTC, sassamori commented on php-rt-iine/post/favo_cancel.php
> +if(isset($_GET['id']) && isset($_SESSION['id'])){
修正コミットのリンクです。
https://github.com/sassamori/takaharusasamori/pull/5/commits/3a167486d6d27777461641a2250c5d850eac493b
自信がないのですが、ご確認よろしくお願い致します。

2020-10-18 10:34 UTC, n06Ar commented on php-rt-iine/post/index.php
> +        $message = $db->prepare('INSERT INTO posts SET member_id=?,message=?,reply_post_id=?,created=NOW()');
こちらの投稿についてですが、ここのSQLを直接実行するとわかりますが、`rt_count`、`delete_flag`、`rted_flag`、`rt_flag`、`rt_member_id`、`rt_post_id`にDefault Valueが設定されていないかつnot nullのカラムなため、insert intoに値の指定がないため失敗します。

2020-10-19 05:54 UTC, sassamori commented on php-rt-iine/post/index.php
> +        $message = $db->prepare('INSERT INTO posts SET member_id=?,message=?,reply_post_id=?,created=NOW()');
失礼いたしました。
6つのカラムにdefault valueを付けました。
Slackで改めてDDL文をお送りしますので、ご確認ください。

2020-10-20 13:48 UTC, n06Ar approved these changes
LGTMです！

2020-10-27 10:43 UTC, merged